# Generated by Django 4.2.14 on 2024-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DororokFavoriteMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_music_id', models.IntegerField()),
                ('artist', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('member_id', models.IntegerField()),
            ],
            options={
                'db_table': 'favorites_music',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DororokListeningMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=255)),
                ('member_id', models.IntegerField()),
            ],
            options={
                'db_table': 'music_listening_log',
                'managed': False,
            },
        ),
    ]
