# Generated by Django 4.2.14 on 2024-08-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_dororokfavoritemusic_dororoklisteningmusic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DororokFavoriteGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
            ],
            options={
                'db_table': 'favorites_genres',
                'managed': False,
            },
        ),
    ]
