# Generated by Django 4.2.14 on 2024-08-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_dororokfavoritegenre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dororokfavoritegenre',
            table='favorite_genres',
        ),
    ]
