# Generated by Django 4.2.14 on 2024-08-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JPOPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': 'JPOP_entry',
            },
        ),
        migrations.CreateModel(
            name='OSTEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': 'OST_entry',
            },
        ),
        migrations.CreateModel(
            name='POPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': 'POP_entry',
            },
        ),
        migrations.CreateModel(
            name='국내 RBSOULEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '국내 RBSOUL_entry',
            },
        ),
        migrations.CreateModel(
            name='국내 랩힙합Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '국내 랩힙합_entry',
            },
        ),
        migrations.CreateModel(
            name='국내 록메탈Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '국내 록메탈_entry',
            },
        ),
        migrations.CreateModel(
            name='국내 밴드Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '국내 밴드_entry',
            },
        ),
        migrations.CreateModel(
            name='국내 포크블루스Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '국내 포크블루스_entry',
            },
        ),
        migrations.CreateModel(
            name='뉴에이지Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '뉴에이지_entry',
            },
        ),
        migrations.CreateModel(
            name='댄스Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '댄스_entry',
            },
        ),
        migrations.CreateModel(
            name='바다Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '바다_entry',
            },
        ),
        migrations.CreateModel(
            name='발라드Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '발라드_entry',
            },
        ),
        migrations.CreateModel(
            name='사랑Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '사랑_entry',
            },
        ),
        migrations.CreateModel(
            name='우정Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '우정_entry',
            },
        ),
        migrations.CreateModel(
            name='인디Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '인디_entry',
            },
        ),
        migrations.CreateModel(
            name='일렉트로니카Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '일렉트로니카_entry',
            },
        ),
        migrations.CreateModel(
            name='재즈Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '재즈_entry',
            },
        ),
        migrations.CreateModel(
            name='클래식Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '클래식_entry',
            },
        ),
        migrations.CreateModel(
            name='트로트Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '트로트_entry',
            },
        ),
        migrations.CreateModel(
            name='해외 RBSOULEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '해외 RBSOUL_entry',
            },
        ),
        migrations.CreateModel(
            name='해외 랩힙합Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '해외 랩힙합_entry',
            },
        ),
        migrations.CreateModel(
            name='해외 록메탈Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '해외 록메탈_entry',
            },
        ),
        migrations.CreateModel(
            name='해외 밴드Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '해외 밴드_entry',
            },
        ),
        migrations.CreateModel(
            name='해외 포크블루스컨트리Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '해외 포크블루스컨트리_entry',
            },
        ),
    ]
