# Generated by Django 4.2.14 on 2024-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_delete_바다entry_delete_사랑entry_delete_우정entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='바다Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '바다_entry',
            },
        ),
        migrations.CreateModel(
            name='사랑Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '사랑_entry',
            },
        ),
        migrations.CreateModel(
            name='우정Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('track_id', models.CharField(max_length=255)),
                ('track_image', models.CharField(default='default.jpg', max_length=255)),
                ('country', models.CharField(default='etc', max_length=255)),
            ],
            options={
                'db_table': '우정_entry',
            },
        ),
    ]
