# Generated by Django 4.2.14 on 2024-07-30 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_jpopentry_table_alter_ostentry_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jpopentry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='jpopentry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='jpopentry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='ostentry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='ostentry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='ostentry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='popentry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='popentry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='popentry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='국내 rbsoulentry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='국내 rbsoulentry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='국내 rbsoulentry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='국내 랩힙합entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='국내 랩힙합entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='국내 랩힙합entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='국내 록메탈entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='국내 록메탈entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='국내 록메탈entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='국내 밴드entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='국내 밴드entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='국내 밴드entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='국내 포크블루스entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='국내 포크블루스entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='국내 포크블루스entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='뉴에이지entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='뉴에이지entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='뉴에이지entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='댄스entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='댄스entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='댄스entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='발라드entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='발라드entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='발라드entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='인디entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='인디entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='인디entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='일렉트로니카entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='일렉트로니카entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='일렉트로니카entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='재즈entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='재즈entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='재즈entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='클래식entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='클래식entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='클래식entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='트로트entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='트로트entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='트로트entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='해외 rbsoulentry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='해외 rbsoulentry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='해외 rbsoulentry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='해외 랩힙합entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='해외 랩힙합entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='해외 랩힙합entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='해외 록메탈entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='해외 록메탈entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='해외 록메탈entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='해외 밴드entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='해외 밴드entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='해외 밴드entry',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='해외 포크블루스컨트리entry',
            name='album',
        ),
        migrations.RemoveField(
            model_name='해외 포크블루스컨트리entry',
            name='album_image',
        ),
        migrations.RemoveField(
            model_name='해외 포크블루스컨트리entry',
            name='rank',
        ),
    ]
