# Generated by Django 4.2.14 on 2024-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_remove_jpopentry_album_remove_jpopentry_album_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jpopentry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='ostentry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='popentry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='국내 rbsoulentry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='국내 랩힙합entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='국내 록메탈entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='국내 밴드entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='국내 포크블루스entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='뉴에이지entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='댄스entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='발라드entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='인디entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='일렉트로니카entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='재즈entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='클래식entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='트로트entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='해외 rbsoulentry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='해외 랩힙합entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='해외 록메탈entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='해외 밴드entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='해외 포크블루스컨트리entry',
            name='track_image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
