# Generated by Django 4.2.14 on 2024-08-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_jpopentry_track_image_ostentry_track_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jpopentry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='ostentry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='popentry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='국내 rbsoulentry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='국내 랩힙합entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='국내 록메탈entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='국내 밴드entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='국내 포크블루스entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='뉴에이지entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='댄스entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='발라드entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='인디entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='일렉트로니카entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='재즈entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='클래식entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='트로트entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='해외 rbsoulentry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='해외 랩힙합entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='해외 록메탈entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='해외 밴드entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
        migrations.AddField(
            model_name='해외 포크블루스컨트리entry',
            name='country',
            field=models.CharField(default='etc', max_length=255),
        ),
    ]
