# Generated by Django 4.2.14 on 2024-07-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='J-POPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'J-POP',
            },
        ),
        migrations.CreateModel(
            name='OSTEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'OST',
            },
        ),
        migrations.CreateModel(
            name='POPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'POP',
            },
        ),
        migrations.CreateModel(
            name='국내 R&B/SOULEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '국내 R&B/SOUL',
            },
        ),
        migrations.CreateModel(
            name='국내 록/메탈Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '국내 록/메탈',
            },
        ),
        migrations.CreateModel(
            name='국내 밴드Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '국내 밴드',
            },
        ),
        migrations.CreateModel(
            name='국내 포크/블루스/컨트리Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '국내 포크/블루스/컨트리',
            },
        ),
        migrations.CreateModel(
            name='국내 포크/블루스Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '국내 포크/블루스',
            },
        ),
        migrations.CreateModel(
            name='뉴에이지Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '뉴에이지',
            },
        ),
        migrations.CreateModel(
            name='댄스Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '댄스',
            },
        ),
        migrations.CreateModel(
            name='발라드Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '발라드',
            },
        ),
        migrations.CreateModel(
            name='인디Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '인디',
            },
        ),
        migrations.CreateModel(
            name='일렉트로니카Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '일렉트로니카',
            },
        ),
        migrations.CreateModel(
            name='재즈Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '재즈',
            },
        ),
        migrations.CreateModel(
            name='클래식Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '클래식',
            },
        ),
        migrations.CreateModel(
            name='트로트Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '트로트',
            },
        ),
        migrations.CreateModel(
            name='해외 R&B/SOULEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '해외 R&B/SOUL',
            },
        ),
        migrations.CreateModel(
            name='해외 록/메탈Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '해외 록/메탈',
            },
        ),
        migrations.CreateModel(
            name='해외 밴드Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '해외 밴드',
            },
        ),
    ]
