# Generated by Django 4.2.14 on 2024-07-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='해외 포크블루스컨트리Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('album_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '해외 포크블루스컨트리',
            },
        ),
        migrations.RenameModel(
            old_name='해외 록/메탈Entry',
            new_name='국내 R&BSOULEntry',
        ),
        migrations.RenameModel(
            old_name='해외 R&B/SOULEntry',
            new_name='국내 랩힙합Entry',
        ),
        migrations.RenameModel(
            old_name='국내 포크/블루스/컨트리Entry',
            new_name='국내 록메탈Entry',
        ),
        migrations.RenameModel(
            old_name='국내 포크/블루스Entry',
            new_name='해외 R&BSOULEntry',
        ),
        migrations.RenameModel(
            old_name='국내 록/메탈Entry',
            new_name='해외 랩 힙합국내 포크블루스Entry',
        ),
        migrations.RenameModel(
            old_name='국내 R&B/SOULEntry',
            new_name='해외 록메탈Entry',
        ),
        migrations.AlterModelTable(
            name='국내 r&bsoulentry',
            table='국내 R&BSOUL',
        ),
        migrations.AlterModelTable(
            name='국내 랩힙합entry',
            table='국내 랩힙합',
        ),
        migrations.AlterModelTable(
            name='국내 록메탈entry',
            table='국내 록메탈',
        ),
        migrations.AlterModelTable(
            name='해외 r&bsoulentry',
            table='해외 R&BSOUL',
        ),
        migrations.AlterModelTable(
            name='해외 랩 힙합국내 포크블루스entry',
            table='해외 랩 힙합국내 포크블루스',
        ),
        migrations.AlterModelTable(
            name='해외 록메탈entry',
            table='해외 록메탈',
        ),
    ]
