# Generated by Django 4.2.14 on 2024-08-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_alter_jpopentry_album_alter_jpopentry_singer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='바다Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '바다',
            },
        ),
        migrations.CreateModel(
            name='사랑Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '사랑',
            },
        ),
        migrations.CreateModel(
            name='우정Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '우정',
            },
        ),
        migrations.DeleteModel(
            name='JPOPEntry',
        ),
        migrations.DeleteModel(
            name='OSTEntry',
        ),
        migrations.DeleteModel(
            name='POPEntry',
        ),
        migrations.DeleteModel(
            name='국내 RBSOULEntry',
        ),
        migrations.DeleteModel(
            name='국내 랩힙합Entry',
        ),
        migrations.DeleteModel(
            name='국내 록메탈Entry',
        ),
        migrations.DeleteModel(
            name='국내 밴드Entry',
        ),
        migrations.DeleteModel(
            name='국내 포크블루스Entry',
        ),
        migrations.DeleteModel(
            name='뉴에이지Entry',
        ),
        migrations.DeleteModel(
            name='댄스Entry',
        ),
        migrations.DeleteModel(
            name='발라드Entry',
        ),
        migrations.DeleteModel(
            name='인디Entry',
        ),
        migrations.DeleteModel(
            name='일렉트로니카Entry',
        ),
        migrations.DeleteModel(
            name='재즈Entry',
        ),
        migrations.DeleteModel(
            name='클래식Entry',
        ),
        migrations.DeleteModel(
            name='트로트Entry',
        ),
        migrations.DeleteModel(
            name='해외 RBSOULEntry',
        ),
        migrations.DeleteModel(
            name='해외 랩힙합Entry',
        ),
        migrations.DeleteModel(
            name='해외 록메탈Entry',
        ),
        migrations.DeleteModel(
            name='해외 밴드Entry',
        ),
        migrations.DeleteModel(
            name='해외 포크블루스컨트리Entry',
        ),
    ]
