# Generated by Django 4.2.14 on 2024-08-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_바다entry_사랑entry_우정entry_delete_jpopentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JPOPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': 'JPOP',
            },
        ),
        migrations.CreateModel(
            name='OSTEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': 'OST',
            },
        ),
        migrations.CreateModel(
            name='POPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': 'POP',
            },
        ),
        migrations.CreateModel(
            name='국내 RBSOULEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '국내 RBSOUL',
            },
        ),
        migrations.CreateModel(
            name='국내 랩힙합Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '국내 랩힙합',
            },
        ),
        migrations.CreateModel(
            name='국내 록메탈Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '국내 록메탈',
            },
        ),
        migrations.CreateModel(
            name='국내 밴드Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '국내 밴드',
            },
        ),
        migrations.CreateModel(
            name='국내 포크블루스Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '국내 포크블루스',
            },
        ),
        migrations.CreateModel(
            name='뉴에이지Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '뉴에이지',
            },
        ),
        migrations.CreateModel(
            name='댄스Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '댄스',
            },
        ),
        migrations.CreateModel(
            name='발라드Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '발라드',
            },
        ),
        migrations.CreateModel(
            name='인디Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '인디',
            },
        ),
        migrations.CreateModel(
            name='일렉트로니카Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '일렉트로니카',
            },
        ),
        migrations.CreateModel(
            name='재즈Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '재즈',
            },
        ),
        migrations.CreateModel(
            name='클래식Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '클래식',
            },
        ),
        migrations.CreateModel(
            name='트로트Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '트로트',
            },
        ),
        migrations.CreateModel(
            name='해외 RBSOULEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '해외 RBSOUL',
            },
        ),
        migrations.CreateModel(
            name='해외 랩힙합Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '해외 랩힙합',
            },
        ),
        migrations.CreateModel(
            name='해외 록메탈Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '해외 록메탈',
            },
        ),
        migrations.CreateModel(
            name='해외 밴드Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '해외 밴드',
            },
        ),
        migrations.CreateModel(
            name='해외 포크블루스컨트리Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '해외 포크블루스컨트리',
            },
        ),
    ]
