# Generated by Django 4.2.14 on 2024-08-14 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0004_jpopentry_ostentry_popentry_국내_rbsoulentry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='바다Entry',
        ),
        migrations.DeleteModel(
            name='사랑Entry',
        ),
        migrations.DeleteModel(
            name='우정Entry',
        ),
    ]
