# Generated by Django 4.2.14 on 2024-08-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0006_바다entry_사랑entry_우정entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='바다Entry',
        ),
        migrations.DeleteModel(
            name='사랑Entry',
        ),
        migrations.DeleteModel(
            name='우정Entry',
        ),
    ]
