# Generated by Django 4.2.14 on 2024-08-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0007_delete_바다entry_delete_사랑entry_delete_우정entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='바다Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '바다',
            },
        ),
        migrations.CreateModel(
            name='사랑Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '사랑',
            },
        ),
        migrations.CreateModel(
            name='우정Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('album_image', models.CharField(max_length=255)),
                ('country', models.CharField(default='etc', max_length=100)),
            ],
            options={
                'db_table': '우정',
            },
        ),
    ]
